Repository OCA/hr-attendance, pull requests merged in 2022-11, with the labels that each got.

#80 [15.0][MIG] hr_attendance_geolocation: Migration to 15.0
  hr_attendance_geolocation/README.rst
  hr_attendance_geolocation/__init__.py
  hr_attendance_geolocation/__manifest__.py
  hr_attendance_geolocation/data/location_data.xml
  hr_attendance_geolocation/i18n/hr_attendance_geolocation.pot
  hr_attendance_geolocation/models/__init__.py
  hr_attendance_geolocation/models/hr_attendance.py
  hr_attendance_geolocation/models/hr_employee.py
  hr_attendance_geolocation/readme/CONTRIBUTORS.rst
  hr_attendance_geolocation/readme/DESCRIPTION.rst
  hr_attendance_geolocation/static/description/icon.png
  hr_attendance_geolocation/static/description/index.html
  hr_attendance_geolocation/static/src/js/attendance_geolocation.js
  hr_attendance_geolocation/tests/__init__.py
  hr_attendance_geolocation/tests/test_hr_attendance_geolocation.py
  hr_attendance_geolocation/views/hr_attendance_views.xml
  setup/hr_attendance_geolocation/odoo/addons/hr_attendance_geolocation
  setup/hr_attendance_geolocation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#85 [15.0][FIX] hr_attendance_geolocation: Correctly set the human representation of latitude (N/S) and longitude (E/W).
  hr_attendance_geolocation/models/hr_attendance.py
Labels: bot is merging ⏳

#83 [15.0][MIG] hr_attendance_autoclose: Migration to 15.0
  hr_attendance_autoclose/README.rst
  hr_attendance_autoclose/__init__.py
  hr_attendance_autoclose/__manifest__.py
  hr_attendance_autoclose/data/hr_attendance.xml
  hr_attendance_autoclose/data/hr_attendance_reason.xml
  hr_attendance_autoclose/data/res_company.xml
  hr_attendance_autoclose/i18n/es.po
  hr_attendance_autoclose/i18n/fr.po
  hr_attendance_autoclose/i18n/hr.po
  hr_attendance_autoclose/i18n/hr_attendance_autoclose.pot
  hr_attendance_autoclose/i18n/it.po
  hr_attendance_autoclose/models/__init__.py
  hr_attendance_autoclose/models/hr_attendance.py
  hr_attendance_autoclose/models/hr_employee.py
  hr_attendance_autoclose/models/res_company.py
  hr_attendance_autoclose/models/res_config_settings.py
  hr_attendance_autoclose/readme/CONTRIBUTORS.rst
  hr_attendance_autoclose/readme/DESCRIPTION.rst
  hr_attendance_autoclose/readme/USAGE.rst
  hr_attendance_autoclose/static/description/icon.png
  hr_attendance_autoclose/static/description/index.html
  hr_attendance_autoclose/tests/__init__.py
  hr_attendance_autoclose/tests/test_hr_attendance_auto_close.py
  hr_attendance_autoclose/views/hr_attendance_view.xml
  hr_attendance_autoclose/views/hr_employee.xml
  hr_attendance_autoclose/views/res_config_settings_view.xml
  setup/hr_attendance_autoclose/odoo/addons/hr_attendance_autoclose
  setup/hr_attendance_autoclose/setup.py
Labels: approved, bot is merging ⏳

#87 Update template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  hr_attendance_sheet/tests/test_attendance_sheet.py
Labels: bot is merging ⏳
