Repository OCA/hr-attendance, pull requests merged in 2022-10, with the labels that each got.

#53 [ADD] 14.0 hr_attendance_validation
  hr_attendance_overtime/i18n/fr.po
  hr_attendance_overtime/models/hr_employee.py
  hr_attendance_overtime/static/src/xml/attendance.xml
  hr_attendance_validation/README.rst
  hr_attendance_validation/__init__.py
  hr_attendance_validation/__manifest__.py
  hr_attendance_validation/data/ir_cron.xml
  hr_attendance_validation/i18n/fr.po
  hr_attendance_validation/i18n/hr_attendance_validation.pot
  hr_attendance_validation/models/__init__.py
  hr_attendance_validation/models/hr_attendance.py
  hr_attendance_validation/models/hr_attendance_validation_sheet.py
  hr_attendance_validation/models/hr_employee.py
  hr_attendance_validation/models/hr_leave.py
  hr_attendance_validation/models/res_config_settings.py
  hr_attendance_validation/models/resource_calendar.py
  hr_attendance_validation/readme/CONFIGURE.rst
  hr_attendance_validation/readme/CONTRIBUTORS.rst
  hr_attendance_validation/readme/DESCRIPTION.rst
  hr_attendance_validation/readme/ROADMAP.rst
  hr_attendance_validation/readme/USAGE.rst
  hr_attendance_validation/security/ir.model.access.csv
  hr_attendance_validation/security/ir.rule.xml
  hr_attendance_validation/static/description/index.html
  hr_attendance_validation/static/src/js/hr_attendance_validation.js
  hr_attendance_validation/static/src/xml/attendance.xml
  hr_attendance_validation/tests/__init__.py
  hr_attendance_validation/tests/test_hr_attendance_validation.py
  hr_attendance_validation/views/assets.xml
  hr_attendance_validation/views/hr_attendance.xml
  hr_attendance_validation/views/hr_attendance_validation.xml
  hr_attendance_validation/views/res_config_settings_views.xml
  setup/hr_attendance_validation/odoo/addons/hr_attendance_validation
  setup/hr_attendance_validation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#75 [14.0][IMP]hr_attendance_reason: turn data into demo data
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/demo/hr_attendance_reason_demo.xml
Labels: approved, bot is merging ⏳

#74 [14.0][IMP]hr_attendance_reason: Make hr.attendance.reason names translatable
  hr_attendance_reason/models/hr_attendance_reason.py
Labels: approved, bot is merging ⏳

#77 hr_attendance_autoclose: remove almost duplicated field worked_hours from tree
  hr_attendance_autoclose/views/hr_attendance_view.xml
Labels: bot is merging ⏳
