Repository OCA/hr-attendance, pull requests merged in 2023-07, with the labels that each got.

#133 [13.0][IMP] hr_attendance_report_theoretical_time: Improve tests to better cover different use cases.
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
Labels: approved, bot is merging ⏳

#124 [15.0][IMP] hr_attendance_reason: Show reasons on attendance screen
  hr_attendance_reason/README.rst
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/data/hr_attendance_reason_data.xml
  hr_attendance_reason/i18n/es.po
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/models/__init__.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/models/hr_employee.py
  hr_attendance_reason/models/hr_employee_base.py
  hr_attendance_reason/models/res_company.py
  hr_attendance_reason/models/res_config_settings.py
  hr_attendance_reason/readme/CONTRIBUTORS.rst
  hr_attendance_reason/static/description/index.html
  hr_attendance_reason/static/src/js/kiosk_confirm.esm.js
  hr_attendance_reason/static/src/js/my_attendances.esm.js
  hr_attendance_reason/static/src/scss/hr_attendance_reason.scss
  hr_attendance_reason/static/src/xml/attendance.xml
  hr_attendance_reason/tests/test_hr_attendance_reason.py
  hr_attendance_reason/views/hr_attendance_reason_view.xml
  hr_attendance_reason/views/res_config_settings_view.xml
Labels: bot is merging ⏳

#135 [14.0][IMP] hr_attendance_report_theoretical_time: Improve tests to better cover different use cases
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
Labels: bot is merging ⏳

#136 [15.0][IMP] hr_attendance_report_theoretical_time: Improve tests to better cover different use cases
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
Labels: bot is merging ⏳

#121 [16.0][MIG] hr_attendance_report_theoretical_time: Migration to 16.0
  hr_attendance_report_theoretical_time/README.rst
  hr_attendance_report_theoretical_time/__init__.py
  hr_attendance_report_theoretical_time/__manifest__.py
  hr_attendance_report_theoretical_time/i18n/bg.po
  hr_attendance_report_theoretical_time/i18n/de.po
  hr_attendance_report_theoretical_time/i18n/es.po
  hr_attendance_report_theoretical_time/i18n/fr.po
  hr_attendance_report_theoretical_time/i18n/hr_attendance_report_theoretical_time.pot
  hr_attendance_report_theoretical_time/i18n/it.po
  hr_attendance_report_theoretical_time/models/__init__.py
  hr_attendance_report_theoretical_time/models/hr_attendance.py
  hr_attendance_report_theoretical_time/models/hr_employee.py
  hr_attendance_report_theoretical_time/models/hr_employee_public.py
  hr_attendance_report_theoretical_time/models/hr_holidays_public.py
  hr_attendance_report_theoretical_time/models/hr_leave.py
  hr_attendance_report_theoretical_time/models/hr_leave_type.py
  hr_attendance_report_theoretical_time/readme/CONFIGURE.rst
  hr_attendance_report_theoretical_time/readme/CONTRIBUTORS.rst
  hr_attendance_report_theoretical_time/readme/CREDITS.rst
  hr_attendance_report_theoretical_time/readme/DESCRIPTION.rst
  hr_attendance_report_theoretical_time/readme/INSTALL.rst
  hr_attendance_report_theoretical_time/readme/ROADMAP.rst
  hr_attendance_report_theoretical_time/readme/USAGE.rst
  hr_attendance_report_theoretical_time/reports/__init__.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_report.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_report_views.xml
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report_views.xml
  hr_attendance_report_theoretical_time/security/hr_attendance_report_theoretical_time_security.xml
  hr_attendance_report_theoretical_time/security/ir.model.access.csv
  hr_attendance_report_theoretical_time/static/description/icon.png
  hr_attendance_report_theoretical_time/static/description/icon.svg
  hr_attendance_report_theoretical_time/static/description/index.html
  hr_attendance_report_theoretical_time/tests/__init__.py
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
  hr_attendance_report_theoretical_time/views/hr_employee_views.xml
  hr_attendance_report_theoretical_time/views/hr_leave_type_views.xml
  hr_attendance_report_theoretical_time/wizards/__init__.py
  hr_attendance_report_theoretical_time/wizards/recompute_theoretical_attendance.py
  hr_attendance_report_theoretical_time/wizards/recompute_theoretical_attendance_views.xml
  hr_attendance_report_theoretical_time/wizards/wizard_theoretical_time.py
  hr_attendance_report_theoretical_time/wizards/wizard_theoretical_time.xml
  setup/hr_attendance_report_theoretical_time/odoo/addons/hr_attendance_report_theoretical_time
  setup/hr_attendance_report_theoretical_time/setup.py
Labels: approved, ready to merge, bot is merging ⏳
