Repository OCA/hr-attendance, pull requests merged in 2023-10, with the labels that each got.

#146 [16.0][MIG] hr_attendance_reason: Migration to 16.0
  hr_attendance_reason/README.rst
  hr_attendance_reason/__init__.py
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/data/hr_attendance_reason_data.xml
  hr_attendance_reason/i18n/bg.po
  hr_attendance_reason/i18n/de.po
  hr_attendance_reason/i18n/es.po
  hr_attendance_reason/i18n/fr.po
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/i18n/it.po
  hr_attendance_reason/models/__init__.py
  hr_attendance_reason/models/hr_attendance.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/models/hr_employee.py
  hr_attendance_reason/models/hr_employee_base.py
  hr_attendance_reason/models/res_company.py
  hr_attendance_reason/models/res_config_settings.py
  hr_attendance_reason/readme/CONTRIBUTORS.rst
  hr_attendance_reason/readme/DESCRIPTION.rst
  hr_attendance_reason/readme/USAGE.rst
  hr_attendance_reason/security/ir.model.access.csv
  hr_attendance_reason/security/security.xml
  hr_attendance_reason/static/description/icon.png
  hr_attendance_reason/static/description/index.html
  hr_attendance_reason/static/src/js/kiosk_confirm.esm.js
  hr_attendance_reason/static/src/js/my_attendances.esm.js
  hr_attendance_reason/static/src/scss/hr_attendance_reason.scss
  hr_attendance_reason/static/src/xml/attendance.xml
  hr_attendance_reason/tests/__init__.py
  hr_attendance_reason/tests/test_hr_attendance_reason.py
  hr_attendance_reason/views/hr_attendance_reason_view.xml
  hr_attendance_reason/views/hr_attendance_view.xml
  hr_attendance_reason/views/res_config_settings_view.xml
  setup/hr_attendance_reason/odoo/addons/hr_attendance_reason
  setup/hr_attendance_reason/setup.py
Labels: bot is merging ⏳

#116 [16.0] [MIG] hr_attendance_autoclose
  hr_attendance_autoclose/README.rst
  hr_attendance_autoclose/__init__.py
  hr_attendance_autoclose/__manifest__.py
  hr_attendance_autoclose/data/hr_attendance.xml
  hr_attendance_autoclose/data/hr_attendance_reason.xml
  hr_attendance_autoclose/data/res_company.xml
  hr_attendance_autoclose/i18n/es.po
  hr_attendance_autoclose/i18n/fr.po
  hr_attendance_autoclose/i18n/hr.po
  hr_attendance_autoclose/i18n/hr_attendance_autoclose.pot
  hr_attendance_autoclose/i18n/it.po
  hr_attendance_autoclose/models/__init__.py
  hr_attendance_autoclose/models/hr_attendance.py
  hr_attendance_autoclose/models/hr_employee.py
  hr_attendance_autoclose/models/res_company.py
  hr_attendance_autoclose/models/res_config_settings.py
  hr_attendance_autoclose/readme/CONTRIBUTORS.rst
  hr_attendance_autoclose/readme/DESCRIPTION.rst
  hr_attendance_autoclose/readme/USAGE.rst
  hr_attendance_autoclose/static/description/icon.png
  hr_attendance_autoclose/static/description/index.html
  hr_attendance_autoclose/tests/__init__.py
  hr_attendance_autoclose/tests/test_hr_attendance_auto_close.py
  hr_attendance_autoclose/views/hr_attendance_view.xml
  hr_attendance_autoclose/views/hr_employee.xml
  hr_attendance_autoclose/views/res_config_settings_view.xml
  setup/hr_attendance_autoclose/odoo/addons/hr_attendance_autoclose
  setup/hr_attendance_autoclose/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#149 [15.0][IMP] hr_attendance: test performance improvement
  hr_attendance_rfid/tests/test_hr_attendance_rfid_process.py
Labels: bot is merging ⏳

#153 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  hr_attendance_calendar_view/README.rst
  hr_attendance_calendar_view/__init__.py
  hr_attendance_calendar_view/i18n/hr_attendance_calendar_view.pot
  hr_attendance_calendar_view/readme/DESCRIPTION.rst
  hr_attendance_calendar_view/static/description/index.html
Labels: help wanted, needs review

#152 [16.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  hr_attendance_calendar_view/README.rst
  hr_attendance_calendar_view/__init__.py
  hr_attendance_calendar_view/readme/DESCRIPTION.rst
  hr_attendance_calendar_view/static/description/index.html
Labels: help wanted, needs review

#151 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  hr_attendance_modification_tracking/i18n/hr_attendance_modification_tracking.pot
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/static/src/js/kiosk_confirm.js
  hr_attendance_reason/static/src/js/my_attendances.js
  hr_attendance_reason/views/hr_attendance_reason_view.xml
  hr_attendance_sheet/i18n/hr_attendance_sheet.pot
  hr_attendance_sheet/views/hr_attendance_sheet.xml
  hr_attendance_validation/i18n/hr_attendance_validation.pot
  hr_attendance_validation/views/hr_attendance_validation.xml
  hr_attendance_validation/views/res_config_settings_views.xml
Labels: help wanted, needs review, bot is merging ⏳
