Repository OCA/hr-attendance, pull requests merged in 2023-01, with the labels that each got.

#99 [13.0][FIX] hr_attendance_geolocation: inheritance
  hr_attendance_geolocation/README.rst
  hr_attendance_geolocation/__manifest__.py
  hr_attendance_geolocation/models/hr_employee.py
  hr_attendance_geolocation/readme/CONTRIBUTORS.rst
  hr_attendance_geolocation/static/description/index.html
  hr_attendance_geolocation/static/src/js/attendance_geolocation.js
  hr_attendance_geolocation/tests/test_hr_attendance_geolocation.py
Labels: approved, bot is merging ⏳

#101 [14.0][FIX] hr_attendance_sheet: Fix tests
  hr_attendance_sheet/tests/test_attendance_sheet.py
Labels: bot is merging ⏳

#100 [14.0][FIX] hr_attendance_geolocation: inheritance
  hr_attendance_geolocation/README.rst
  hr_attendance_geolocation/__manifest__.py
  hr_attendance_geolocation/models/hr_employee.py
  hr_attendance_geolocation/readme/CONTRIBUTORS.rst
  hr_attendance_geolocation/static/description/index.html
  hr_attendance_geolocation/static/src/js/attendance_geolocation.js
  hr_attendance_geolocation/tests/test_hr_attendance_geolocation.py
Labels: bot is merging ⏳

#91 [14.0][IMP] hr_attendance_rfid: Change assertNotEquals to assertNotEqual
  hr_attendance_rfid/tests/test_hr_attendance_rfid_process.py
Labels: bot is merging ⏳

#95 [16.0][MIG] hr_attendance_geolocation
  hr_attendance_geolocation/README.rst
  hr_attendance_geolocation/__init__.py
  hr_attendance_geolocation/__manifest__.py
  hr_attendance_geolocation/data/location_data.xml
  hr_attendance_geolocation/i18n/hr_attendance_geolocation.pot
  hr_attendance_geolocation/models/__init__.py
  hr_attendance_geolocation/models/hr_attendance.py
  hr_attendance_geolocation/models/hr_employee.py
  hr_attendance_geolocation/readme/CONTRIBUTORS.rst
  hr_attendance_geolocation/readme/DESCRIPTION.rst
  hr_attendance_geolocation/static/description/icon.png
  hr_attendance_geolocation/static/description/index.html
  hr_attendance_geolocation/static/src/js/attendance_geolocation.js
  hr_attendance_geolocation/tests/__init__.py
  hr_attendance_geolocation/tests/test_hr_attendance_geolocation.py
  hr_attendance_geolocation/views/hr_attendance_views.xml
  setup/hr_attendance_geolocation/odoo/addons/hr_attendance_geolocation
  setup/hr_attendance_geolocation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#105 [15.0][FIX] hr_attendance_report_theoretical_time: tests
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
Labels: approved, bot is merging ⏳

#104 [15.0][IMP] hr_attendance_geolocation: Refactor javascript
  hr_attendance_geolocation/README.rst
  hr_attendance_geolocation/__manifest__.py
  hr_attendance_geolocation/readme/CONTRIBUTORS.rst
  hr_attendance_geolocation/static/description/index.html
  hr_attendance_geolocation/static/src/js/attendance_geolocation.js
  hr_attendance_geolocation/static/src/js/geolocation_service_legacy.js
  hr_attendance_geolocation/static/src/js/geolocation_user_context_legacy.esm.js
Labels: approved, bot is merging ⏳
