Repository OCA/hr-attendance, pull requests merged in 2023-04, with the labels that each got.

#102 [14.0][IMP] hr_attendance_reason: Show reasons on attendance screen
  hr_attendance_reason/README.rst
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/demo/hr_attendance_reason_demo.xml
  hr_attendance_reason/i18n/es.po
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/models/__init__.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/models/hr_employee.py
  hr_attendance_reason/models/hr_employee_base.py
  hr_attendance_reason/models/res_company.py
  hr_attendance_reason/models/res_config_settings.py
  hr_attendance_reason/readme/CONTRIBUTORS.rst
  hr_attendance_reason/static/description/index.html
  hr_attendance_reason/static/src/js/kiosk_confirm.js
  hr_attendance_reason/static/src/js/my_attendances.js
  hr_attendance_reason/static/src/scss/hr_attendance_reason.scss
  hr_attendance_reason/static/src/xml/attendance.xml
  hr_attendance_reason/tests/test_hr_attendance_reason.py
  hr_attendance_reason/views/assets.xml
  hr_attendance_reason/views/hr_attendance_reason_view.xml
  hr_attendance_reason/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳

#120 [13.0][IMP] hr_attendance_reason: Add required reason on attendance screen option
  hr_attendance_reason/i18n/es.po
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/models/hr_employee_base.py
  hr_attendance_reason/models/res_company.py
  hr_attendance_reason/models/res_config_settings.py
  hr_attendance_reason/static/src/js/kiosk_confirm.js
  hr_attendance_reason/static/src/js/my_attendances.js
  hr_attendance_reason/static/src/xml/attendance.xml
  hr_attendance_reason/views/res_config_settings_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#123 [14.0][IMP] hr_attendance_reason: Add required reason on attendance screen option
  hr_attendance_reason/i18n/es.po
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/models/hr_employee_base.py
  hr_attendance_reason/models/res_company.py
  hr_attendance_reason/models/res_config_settings.py
  hr_attendance_reason/static/src/js/kiosk_confirm.js
  hr_attendance_reason/static/src/js/my_attendances.js
  hr_attendance_reason/static/src/xml/attendance.xml
  hr_attendance_reason/views/res_config_settings_view.xml
Labels: bot is merging ⏳

#122 [15.0] hr_attendance_calendar_view: Add calendar view to attendance
  hr_attendance_calendar_view/__manifest__.py
  hr_attendance_calendar_view/views/hr_attendance_calendar_views.xml
  setup/hr_attendance_calendar_view/odoo/addons/hr_attendance_calendar_view
  setup/hr_attendance_calendar_view/setup.py
Labels: bot is merging ⏳
