Repository OCA/hr-attendance, pull requests merged in 2023-02, with the labels that each got.

#106 [13.0][IMP] hr_attendance_reason: Add multi-company option + security rule
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/security/security.xml
  hr_attendance_reason/views/hr_attendance_reason_view.xml
Labels: approved, bot is merging ⏳

#108 [14.0][FIX] hr_attendance_sheet: Add freeze_time to test to prevent errors sometimes
  hr_attendance_sheet/tests/test_attendance_sheet.py
Labels: approved, bot is merging ⏳

#107 [14.0][IMP] hr_attendance_reason: Add multi-company option + security rule
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/security/security.xml
  hr_attendance_reason/views/hr_attendance_reason_view.xml
Labels: bot is merging ⏳

#109 [15.0][IMP] hr_attendance_reason: Add multi-company option + security rule
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/security/security.xml
  hr_attendance_reason/views/hr_attendance_reason_view.xml
Labels: approved, bot is merging ⏳

#111 [13.0][FIX] hr_attendance_reason: Prevent access error when a basic user tries to create an attendance.
  hr_attendance_reason/models/__init__.py
  hr_attendance_reason/models/hr_employee.py
  hr_attendance_reason/models/hr_employee_base.py
  hr_attendance_reason/tests/test_hr_attendance_reason.py
Labels: approved, bot is merging ⏳

#110 [FIX] hr_attendance_modification_tracking: Set related fields as not tracking
  hr_attendance_modification_tracking/models/__init__.py
  hr_attendance_modification_tracking/models/hr_employee.py
Labels: approved, bot is merging ⏳

#86 [14.0][MIG] hr_birthday_welcome_message: migration to 14.0
  hr_birthday_welcome_message/README.rst
  hr_birthday_welcome_message/__init__.py
  hr_birthday_welcome_message/__manifest__.py
  hr_birthday_welcome_message/i18n/hr_birthday_welcome_message.pot
  hr_birthday_welcome_message/models/__init__.py
  hr_birthday_welcome_message/models/hr_employee.py
  hr_birthday_welcome_message/readme/CONTRIBUTORS.rst
  hr_birthday_welcome_message/readme/DESCRIPTION.rst
  hr_birthday_welcome_message/static/description/icon.png
  hr_birthday_welcome_message/static/description/index.html
  hr_birthday_welcome_message/static/src/js/greeting_message.js
  hr_birthday_welcome_message/templates/assets.xml
  hr_birthday_welcome_message/tests/__init__.py
  hr_birthday_welcome_message/tests/test_hr_birthday_welcome_message.py
  setup/hr_birthday_welcome_message/odoo/addons/hr_birthday_welcome_message
  setup/hr_birthday_welcome_message/setup.py
Labels: approved, ready to merge, bot is merging ⏳
