Repository OCA/hr-attendance, pull requests merged in 2024-08, with the labels that each got.

#174 [17.0][MIG] hr_attendance_calendar_view: Migration to 17.0
  hr_attendance_calendar_view/README.rst
  hr_attendance_calendar_view/__init__.py
  hr_attendance_calendar_view/__manifest__.py
  hr_attendance_calendar_view/i18n/hr_attendance_calendar_view.pot
  hr_attendance_calendar_view/i18n/it.po
  hr_attendance_calendar_view/pyproject.toml
  hr_attendance_calendar_view/readme/CONTRIBUTORS.md
  hr_attendance_calendar_view/readme/DESCRIPTION.md
  hr_attendance_calendar_view/static/description/icon.png
  hr_attendance_calendar_view/static/description/index.html
  hr_attendance_calendar_view/views/hr_attendance_calendar_views.xml
Labels: approved, bot is merging ⏳

#178 [17.0][MIG] hr_attendance_reason: Migration to version 17.0
  hr_attendance_reason/README.rst
  hr_attendance_reason/__init__.py
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/controllers/__init__.py
  hr_attendance_reason/controllers/main.py
  hr_attendance_reason/data/hr_attendance_reason_data.xml
  hr_attendance_reason/i18n/bg.po
  hr_attendance_reason/i18n/de.po
  hr_attendance_reason/i18n/es.po
  hr_attendance_reason/i18n/fr.po
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/i18n/it.po
  hr_attendance_reason/models/__init__.py
  hr_attendance_reason/models/hr_attendance.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/models/hr_employee.py
  hr_attendance_reason/models/res_company.py
  hr_attendance_reason/models/res_config_settings.py
  hr_attendance_reason/pyproject.toml
  hr_attendance_reason/readme/CONTRIBUTORS.md
  hr_attendance_reason/readme/DESCRIPTION.md
  hr_attendance_reason/readme/USAGE.md
  hr_attendance_reason/security/ir.model.access.csv
  hr_attendance_reason/security/security.xml
  hr_attendance_reason/static/description/icon.png
  hr_attendance_reason/static/description/index.html
  hr_attendance_reason/static/src/components/attendance_menu/attendance_menu.esm.js
  hr_attendance_reason/static/src/components/attendance_menu/attendance_menu.xml
  hr_attendance_reason/static/src/components/kiosk_reason/kiosk_reason.esm.js
  hr_attendance_reason/static/src/components/kiosk_reason/kiosk_reason.xml
  hr_attendance_reason/static/src/components/public_kiosk/public_kiosk_app.esm.js
  hr_attendance_reason/static/src/components/public_kiosk/public_kiosk_app.xml
  hr_attendance_reason/static/src/js/rpc_service.esm.js
  hr_attendance_reason/static/src/scss/hr_attendance_reason.scss
  hr_attendance_reason/tests/__init__.py
  hr_attendance_reason/tests/test_hr_attendance_reason.py
  hr_attendance_reason/views/hr_attendance_reason_view.xml
  hr_attendance_reason/views/hr_attendance_view.xml
  hr_attendance_reason/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳

#155 [IMP] hr_attendance_validation: Ignoring some leave types
  hr_attendance_validation/README.rst
  hr_attendance_validation/__manifest__.py
  hr_attendance_validation/i18n/fr.po
  hr_attendance_validation/i18n/hr_attendance_validation.pot
  hr_attendance_validation/i18n/it.po
  hr_attendance_validation/models/__init__.py
  hr_attendance_validation/models/hr_attendance_validation_sheet.py
  hr_attendance_validation/models/hr_leave_type.py
  hr_attendance_validation/readme/CONFIGURE.rst
  hr_attendance_validation/static/description/index.html
  hr_attendance_validation/tests/test_hr_attendance_validation.py
  hr_attendance_validation/views/hr_leave_type.xml
Labels: approved, bot is merging ⏳, stale

#179 [17.0][MIG] hr_attendance_autoclose: Migration to version 17.0
  hr_attendance_autoclose/README.rst
  hr_attendance_autoclose/__init__.py
  hr_attendance_autoclose/__manifest__.py
  hr_attendance_autoclose/data/hr_attendance.xml
  hr_attendance_autoclose/data/hr_attendance_reason.xml
  hr_attendance_autoclose/data/res_company.xml
  hr_attendance_autoclose/i18n/es.po
  hr_attendance_autoclose/i18n/fr.po
  hr_attendance_autoclose/i18n/hr.po
  hr_attendance_autoclose/i18n/hr_attendance_autoclose.pot
  hr_attendance_autoclose/i18n/it.po
  hr_attendance_autoclose/models/__init__.py
  hr_attendance_autoclose/models/hr_attendance.py
  hr_attendance_autoclose/models/hr_employee.py
  hr_attendance_autoclose/models/res_company.py
  hr_attendance_autoclose/models/res_config_settings.py
  hr_attendance_autoclose/pyproject.toml
  hr_attendance_autoclose/readme/CONTRIBUTORS.md
  hr_attendance_autoclose/readme/DESCRIPTION.md
  hr_attendance_autoclose/readme/USAGE.md
  hr_attendance_autoclose/static/description/icon.png
  hr_attendance_autoclose/static/description/index.html
  hr_attendance_autoclose/tests/__init__.py
  hr_attendance_autoclose/tests/test_hr_attendance_auto_close.py
  hr_attendance_autoclose/views/hr_attendance_view.xml
  hr_attendance_autoclose/views/hr_employee.xml
  hr_attendance_autoclose/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳

#173 [17.0][MIG] hr_attendance_report_theoretical_time: Migration to version 17.0
  hr_attendance_report_theoretical_time/README.rst
  hr_attendance_report_theoretical_time/__init__.py
  hr_attendance_report_theoretical_time/__manifest__.py
  hr_attendance_report_theoretical_time/i18n/bg.po
  hr_attendance_report_theoretical_time/i18n/de.po
  hr_attendance_report_theoretical_time/i18n/es.po
  hr_attendance_report_theoretical_time/i18n/fr.po
  hr_attendance_report_theoretical_time/i18n/hr_attendance_report_theoretical_time.pot
  hr_attendance_report_theoretical_time/i18n/it.po
  hr_attendance_report_theoretical_time/models/__init__.py
  hr_attendance_report_theoretical_time/models/hr_attendance.py
  hr_attendance_report_theoretical_time/models/hr_employee.py
  hr_attendance_report_theoretical_time/models/hr_employee_public.py
  hr_attendance_report_theoretical_time/models/hr_holidays_public.py
  hr_attendance_report_theoretical_time/models/hr_leave.py
  hr_attendance_report_theoretical_time/models/hr_leave_type.py
  hr_attendance_report_theoretical_time/pyproject.toml
  hr_attendance_report_theoretical_time/readme/CONFIGURE.md
  hr_attendance_report_theoretical_time/readme/CONTRIBUTORS.md
  hr_attendance_report_theoretical_time/readme/CREDITS.md
  hr_attendance_report_theoretical_time/readme/DESCRIPTION.md
  hr_attendance_report_theoretical_time/readme/INSTALL.md
  hr_attendance_report_theoretical_time/readme/ROADMAP.md
  hr_attendance_report_theoretical_time/readme/USAGE.md
  hr_attendance_report_theoretical_time/reports/__init__.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_report_views.xml
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report_views.xml
  hr_attendance_report_theoretical_time/security/hr_attendance_report_theoretical_time_security.xml
  hr_attendance_report_theoretical_time/security/ir.model.access.csv
  hr_attendance_report_theoretical_time/static/description/icon.png
  hr_attendance_report_theoretical_time/static/description/icon.svg
  hr_attendance_report_theoretical_time/static/description/index.html
  hr_attendance_report_theoretical_time/tests/__init__.py
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
  hr_attendance_report_theoretical_time/views/hr_employee_views.xml
  hr_attendance_report_theoretical_time/views/hr_leave_type_views.xml
  hr_attendance_report_theoretical_time/wizards/__init__.py
  hr_attendance_report_theoretical_time/wizards/recompute_theoretical_attendance.py
  hr_attendance_report_theoretical_time/wizards/recompute_theoretical_attendance_views.xml
  hr_attendance_report_theoretical_time/wizards/wizard_theoretical_time.py
  hr_attendance_report_theoretical_time/wizards/wizard_theoretical_time.xml
Labels: approved, ready to merge, bot is merging ⏳
