Repository OCA/hr-attendance, pull requests merged in 2025-03, with the labels that each got.

#214 [17.0][FIX] hr_attendance_reason: remove 'manual_selection' route
  hr_attendance_reason/controllers/main.py
Labels: approved, merged 🎉

#209 [15.0][FIX] hr_attendance_geolocation: correctly display the seconds symbol
  hr_attendance_geolocation/models/hr_attendance.py
Labels: approved, bot is merging ⏳

#217 [16.0][FIX] hr_attendance_geolocation: correctly display the seconds symbol
  hr_attendance_geolocation/models/hr_attendance.py
Labels: bot is merging ⏳

#169 [16.0] [MIG] hr_birthday_welcome_message: Migration to 16.0
  hr_birthday_welcome_message/README.rst
  hr_birthday_welcome_message/__init__.py
  hr_birthday_welcome_message/__manifest__.py
  hr_birthday_welcome_message/i18n/es.po
  hr_birthday_welcome_message/i18n/hr_birthday_welcome_message.pot
  hr_birthday_welcome_message/i18n/it.po
  hr_birthday_welcome_message/models/__init__.py
  hr_birthday_welcome_message/models/hr_employee.py
  hr_birthday_welcome_message/readme/CONFIGURE.rst
  hr_birthday_welcome_message/readme/CONTRIBUTORS.rst
  hr_birthday_welcome_message/readme/DESCRIPTION.rst
  hr_birthday_welcome_message/readme/USAGE.rst
  hr_birthday_welcome_message/static/description/icon.png
  hr_birthday_welcome_message/static/description/index.html
  hr_birthday_welcome_message/static/src/js/greeting_message.js
  hr_birthday_welcome_message/tests/__init__.py
  hr_birthday_welcome_message/tests/test_hr_birthday_welcome_message.py
  setup/hr_birthday_welcome_message/odoo/addons/hr_birthday_welcome_message
  setup/hr_birthday_welcome_message/setup.py
Labels: bot is merging ⏳
